services:
  - type: worker
    name: telegram-bot
    env: python
    pythonVersion: 3.11.8 # Явно указываем версию Python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
